###########################################################
# Dockerfile to build Ergatis core image
# Based on Alpine Linux
############################################################

FROM adkinsrs/workflow:3.2.0-alpine

MAINTAINER Shaun Adkins <sadkins@som.umaryland.edu>

EXPOSE 80

#--------------------------------------------------------------------------------
# BASICS

# 1) Install general things
# 2) Install Perl things

RUN apk add --no-cache \
	autoconf \
	build-base \
	git \
	perl \
	perl-app-cpanminus \
	perl-cgi-session \
	perl-config-inifiles \
	perl-cpan-meta-check \
	perl-date-manip \
	perl-dev \
	perl-html-template \
	perl-io-tee \
	perl-json \
	perl-log-log4perl \
	perl-xml-libxml \
	perl-xml-parser \
	perl-xml-rss \
	perl-xml-twig \
	perl-xml-writer \
	php5 \
	vim \
	wget \
	zip unzip \
	zlib-dev

RUN cpanm --force \
	#dh-make-perl \
	CDB_File \
	File::Mirror \
	File::Spec \
	Log::Cabin \
	Math::Combinatorics \
	PerlIO::gzip \
	Term::ProgressBar

# Make various directories.
# /opt/packages is where software installs will be placed or symlinked to
# /var/www/html is where the Ergatis site and pipeline building UI will be
RUN chmod 777 /opt \
       && mkdir /opt/packages && chmod 777 /opt/packages \
       && mkdir -p /var/www/html && chmod 777 /var/www/html

#--------------------------------------------------------------------------------
# SCRATCH

RUN mkdir -m 0777 -p /usr/local/scratch \
	&& mkdir -m 0777 /usr/local/scratch/ergatis \
	&& mkdir -m 0777 /usr/local/scratch/ergatis/archival \
	&& mkdir -m 0777 /usr/local/scratch/workflow  \
	&& mkdir -m 0777 /usr/local/scratch/workflow/id_repository  \
	&& mkdir -m 0777 /usr/local/scratch/workflow/runtime \
	&& mkdir -m 0777 /usr/local/scratch/workflow/runtime/pipeline \
	&& mkdir -m 0777 /usr/local/scratch/workflow/scripts \
	&& mkdir -m 0777 /tmp/pipelines_building 

#--------------------------------------------------------------------------------
# ERGATIS SETUP

# Set up lib directory
RUN mkdir -p /opt/ergatis/lib/
COPY lib/ /opt/ergatis/lib/
ENV PERL5LIB=/opt/ergatis/lib/perl5

# Set up site
RUN mkdir /var/www/html/ergatis
COPY htdocs/ /var/www/html/ergatis/
COPY ergatis.ini /var/www/html/ergatis/cgi/

# Change the level of debugging
COPY log4j.properties /opt/workflow/

# Set up area to store scripts
RUN mkdir -p /opt/scripts
COPY create_wrappers.sh /opt/scripts
COPY perl2wrapper_ergatis.pl /opt/scripts
COPY python2wrapper_ergatis.pl /opt/scripts
COPY julia2wrapper_ergatis.pl /opt/scripts

# Lastly, set working directory to root directory
WORKDIR /
CMD ["/bin/bash"]
