###########################################################
# Dockerfile to build Ergatis directory structure and install libraries
# Has no function as an independent image
# Based on Alpine Linux
############################################################

#FROM adkinsrs/workflow:3.2.0-alpine
FROM alpine:3.8

MAINTAINER Shaun Adkins <sadkins@som.umaryland.edu>

#--------------------------------------------------------------------------------
# BASICS

# 1) Install general things
# 2) Install Perl things

RUN apk add --no-cache \
	autoconf \
	build-base \
	curl \
	git \
	perl \
	perl-app-cpanminus \
	perl-cgi-session \
	perl-config-inifiles \
	perl-cpan-meta-check \
	perl-date-manip \
	perl-dev \
	perl-html-template \
	perl-io-tee \
	perl-json \
	perl-log-log4perl \
	perl-xml-libxml \
	perl-xml-parser \
	perl-xml-rss \
	perl-xml-twig \
	perl-xml-writer \
	vim \
	wget \
	zip unzip \
	zlib-dev \
&& cpanm --force \
	#dh-make-perl \
	CDB_File \
	File::Mirror \
	File::Spec \
	Log::Cabin \
	PerlIO::gzip \
	Term::ProgressBar

# Make various directories.
# /opt/packages is where software installs will be placed or symlinked to
RUN mkdir -p /opt/packages && chmod 777 /opt/packages \
       && mkdir -p /var/www/html/config && chmod 777 /var/www/html/config

#--------------------------------------------------------------------------------
# SCRATCH

RUN mkdir -m 0777 -p /usr/local/scratch \
	&& mkdir -m 0777 /usr/local/scratch/ergatis \
	&& mkdir -m 0777 /usr/local/scratch/ergatis/archival \
	&& mkdir -m 0777 /usr/local/scratch/workflow  \
	&& mkdir -m 0777 /usr/local/scratch/workflow/id_repository  \
	&& mkdir -m 0777 /usr/local/scratch/workflow/runtime \
	&& mkdir -m 0777 /usr/local/scratch/workflow/runtime/pipeline \
	&& mkdir -m 0777 /usr/local/scratch/workflow/scripts \
	&& mkdir -m 0777 /tmp/pipelines_building 

#--------------------------------------------------------------------------------
# ERGATIS SETUP

# Set up lib directory
RUN mkdir -p /opt/ergatis/lib/perl5
ENV PERL5LIB=/opt/ergatis/lib/perl5

# Add Ergatis.ini config file
COPY ergatis.ini /var/www/html/config

# Set up area to store scripts
RUN mkdir -p /opt/scripts

# Lastly, set working directory to root directory
WORKDIR /
CMD ["/bin/bash"]
